project:
  type: website
  output-dir: docs
  render:
  - index.qmd
  - day1_practical.qmd
  - day1_practical_2.qmd
  - day2_practical_3.qmd
  # - day2_practical_4.qmd
  # - day3_practical_5.qmd
  # - day4_practical_6.qmd
  # - day5_practical_8.qmd
  - slides/slides_1.qmd
  - slides/slides_2.qmd
  - slides/slides_3.qmd
  # - slides/slides_4.qmd
  # - slides/slides_5.qmd
  # - slides/slides_10.qmd
  # - slides/slides_12.qmd
  # - slides/slides_13.qmd
website:
  title: inlabru workshop
  navbar:
    logo: INLA_logo.png
    left:
    - href: index.qmd
      text: Home
  sidebar:
    style: docked
    search: true
    contents:
    - index.qmd
    - day1_practical.qmd
    - day1_practical_2.qmd
    - day2_practical_3.qmd
    - day2_practical_4.qmd
    - day3_practical_5.qmd
    - day4_practical_6.qmd
    - day5_practical_8.qmd
  page-navigation: true
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css:
    - styles.css
    - include/webex.css
    toc: true
    include-after-body: include/webex.js
editor: visual

