project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - day1_practical.qmd
    - day1_practical_2.qmd
    - day2_practical_3.qmd
    - day2_practical_4.qmd
    - day3_practical_5.qmd
    - day4_practical_6.qmd
    - day5_practical_8.qmd
    - day5_practical_9.qmd
    # - slides/slides_1.qmd
    - slides/slides_2.qmd
    - slides/slides_3.qmd
    - slides/slides_4.qmd
    - slides/slides_5.qmd
    - slides/slides_10.qmd
    - slides/slides_12.qmd
    - slides/slides_13.qmd

website:
  title: inlabru workshop
  navbar:
    logo: INLA_logo.png
    left:
      - href: index.qmd
        text: Home
  sidebar:
    style: docked
    search: true
    contents:
      - href: index.html
        text: Home

      - section: "Slides"
        contents:
          - href: slides/slides_2.html
            text: Lecture 1 
          - href: slides/slides_3.html
            text: Lecture 2
          - href: slides/slides_4.html
            text: Lecture 3
          - href: slides/slides_5.html
            text: Lecture 4
          - href: slides/slides_10.html
            text: Lecture 9
          - href: slides/slides_12.html
            text: Lecture 11
          - href: slides/slides_13.html
            text: Lecture 12

      - section: "Practicals"
        contents:
          - href: day1_practical.html
            text: Practical 1
          - href: day1_practical_2.html
            text: Practical 2
          - href: day2_practical_3.html
            text: Practical 3
          - href: day2_practical_4.html
            text: Practical 4
          - href: day3_practical_5.html
            text: Practical 5
          - href: day4_practical_6.html
            text: Practical 6
          - text: Practical 7
            href: day5_practical_7.html
          - text: Practical 8
            href: day5_practical_8.html
            external: true
          - text: Practical 9
            href: day5_practical_9.html
            external: true

   
  page-navigation: true

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css:
      - styles.css
      - include/webex.css
    toc: true
    include-after-body: include/webex.js

editor: visual

execute:
  freeze: false
